# base
seed: 0
deterministic: True

# environment config
device: cpu                           # examples: [0], [0,1], [1,2,3], cpu, mps... 

# project config
project: outputs/bert_classifier
name: google_store_review

# model config
pretrained_model: bert-base-uncased   # [bert-base-uncased, bert-base-cased, bert-large-uncased, ...] Hugging Face's pre-trained BERT model path
max_len: 512
class_num: 3                          # The number of classes of the BERT classifier


# data config
workers: 0                            # Don't worry to set worker. The number of workers will be set automatically according to the batch size.
google_store_review_train: True       # if True, Google store reivew data will be loaded automatically.
class_num: 10                         # Number of image label classes.
google_store_review:
    path: data/
    trainset_prop: 0.8                # The ratio of the data used for training. If it is set to 0.8, then the validation and test data will each be set to a ratio of 0.1.
CUSTOM:
    train_data_path: null
    validation_data_path: null
    test_data_path: null

# train config
batch_size: 64
epochs: 100
lr: 1e-4
patience: 10                          # Early stopping epochs

# logging config
common: ['train_loss', 'train_acc', 'validation_loss', 'validation_acc', 'lr']